export const tagTypes = {
  auth: "Auth",
  users: "Users",
  user: "User",
  otp: "Otp",
  transformationPosts: "TransformationPosts",
  categories: "Categories",
  category: "Category",
  subCategories: "SubCategories",
  subCategory: "SubCategory",
  packages: "Packages",
  messages: "Messages",
  notifications: "Notifications",
  comments: "Comments",
  serviceProviders: "ServiceProviders",
  serviceProvider: "ServiceProvider",
  servicePosts: "ServicePosts",
  servicePost: "ServicePost",
  myServicePosts: "MyServicePosts",
  services: "Services",
  contracts: "Contracts",
  contract: "Contract",
  reviews: "Reviews",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.users,
  tagTypes.otp,
  tagTypes.transformationPosts,
  tagTypes.categories,
  tagTypes.category,
  tagTypes.subCategories,
  tagTypes.subCategory,
  tagTypes.packages,
  tagTypes.messages,
  tagTypes.notifications,
  tagTypes.comments,
  tagTypes.serviceProviders,
  tagTypes.serviceProvider,
  tagTypes.servicePosts,
  tagTypes.servicePost,
  tagTypes.myServicePosts,
  tagTypes.services,
  tagTypes.contracts,
  tagTypes.contract,
  tagTypes.reviews,
];
