export const tagTypes = {
  auth: "Auth",
  user: "User",
  otp: "Otp",
  wishlist: "Wishlist",
  category: "Category",
  review: "Review",
  products: "Products",
  newProducts: "NewProducts",
  product: "Product",
  orders: "Orders",
  order: "Order",
  shop: "Shop",
  payment: "Payment",
  content: "Content",
  refund: "Refund",
  notification: "notification",
  income: "income",
  package:"package",
  category: "category",
  subcategory: "subcategory",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.otp,
  tagTypes.wishlist,
  tagTypes.category,
  tagTypes.review,
  tagTypes.products,
  tagTypes.newProducts,
  tagTypes.product,
  tagTypes.orders,
  tagTypes.order,
  tagTypes.shop,
  tagTypes.payment,
  tagTypes.content,
  tagTypes.refund,
  tagTypes.notification,
  tagTypes.income,
  tagTypes.package,
  tagTypes.category,
  tagTypes.subcategory,
];
